# Since this playbook performs the initial setup for our PIs,
# they may not be part of our inventory yet.
# To run this playbook against some hosts use a command like
# ansible-playbook -i "bananaGuard02," initialSetup.yml
# The trailing ',' in the inventory string is important
# to make it distinguishable from a file.
# Inspired by:
# https://stackoverflow.com/a/18195217/448591
- hosts: all
  remote_user: pi
  become: yes
  become_method: sudo
  tasks:
    - name: Set authorized key for user pi
      authorized_key:
        user: pi
        key: "{{ lookup('file', '/home/mushu/.ssh/bananaGuards.pub') }}"
    - name: Disable password for user pi
      command: /usr/bin/passwd -d pi
    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"
    - name: Updating package caches
      apt: update_cache=yes
    - name: Upgrading machines
      apt: upgrade=dist
    - name: Install vim
      apt: name=vim state=present
    - name: Install docker
      apt: name=docker.io state=present
    # Restarting host:
    # https://support.ansible.com/hc/en-us/articles/201958037-Reboot-a-server-and-wait-for-it-to-come-back
    - name: Restart machine
      shell: sleep 2 && shutdown -r now "Triggered by ansible playbook initialSetup.yml"
      async: 1
      poll: 0
      sudo: true
      ignore_errors: true
