# Since this playbook performs the initial setup for our PIs,
# they may not be part of our inventory yet.
# To run this playbook against some hosts use a command like
# ansible-playbook -i "bananaGuard02," initialSetup.yml
# The trailing ',' in the inventory string is important
# to make it distinguishable from a file.
# Inspired by:
# https://stackoverflow.com/a/18195217/448591
- hosts: all
  remote_user: pirate
  tasks:
    - name: Set authorized key for user pirate
      authorized_key:
        user: pirate
        key: "{{ lookup('file', '/home/mushu/.ssh/bananaGuards.pub') }}"
    - name: Disable password for user pirate
      become: yes
      command: /usr/bin/passwd -d pirate
    - name: Set /boot/device-init.yaml
      become: yes
      template:
        src: templates/device-init.j2
        dest: /boot/device-init.yaml
        owner: root
        group: root
        mode: "u=rwx,g=rx,o=rx"
    - name: Updating package caches
      become: yes
      apt: update_cache=yes
    - name: Upgrading machines
      become: yes
      apt: upgrade=dist
    - name: Install vim
      become: yes
      apt: name=vim state=present
    - name: Install git
      become: yes
      apt: name=git state=present
    - name: Checkout git repo
      git:
        repo: https://github.com/runjak/BananaGuards.git
        dest: /home/pirate/BananaGuards
    - name: Restart machine
      become: yes
      shell: sleep 2 && shutdown -r now "Triggered by ansible playbook initialSetup.yml"
      async: 1
      poll: 0
      ignore_errors: true
