# Inspired by:
# https://techsomnia.net/2013/11/ansible-apt-get-updateupgrade/
# https://docs.ansible.com/ansible/apt_module.html
- hosts: bananaGuards
  remote_user: pirate
  become: yes
  become_method: sudo
  tasks:
    - name: Update a server
      apt: update_cache=yes
    - name: Upgrade a server
      apt: upgrade=dist
    - name: Restart machine
      become: yes
      shell: sleep 2 && shutdown -r now "Triggered by ansible playbook initialSetup.yml"
      async: 1
      poll: 0
      ignore_errors: true
